# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1TM73nuGsaVNeIGE_GdsE_4KPy86vC6mo
"""

import streamlit as st
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
from sklearn.preprocessing import MinMaxScaler
from sklearn.cluster import KMeans
import matplotlib.pyplot as plt

st.set_page_config(page_title="Iris K-Means Clustering", layout="centered")

st.title("🌸 Iris Flower Clustering with K-Means")
st.write(
    "This app clusters iris flowers using **petal length** and **petal width**, "
    "with optional scaling, an elbow plot to pick K, and a cluster scatter plot."
)

# ---- Load data ----
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df = df[["petal length (cm)", "petal width (cm)"]]

st.subheader("Data (petal length & width only)")
st.dataframe(df.head())

# ---- Preprocessing option ----
scale_data = st.checkbox("Apply MinMax Scaling", value=True)

if scale_data:
    scaler = MinMaxScaler()
    X = scaler.fit_transform(df)
    X = pd.DataFrame(X, columns=df.columns)
else:
    X = df.copy()

# ---- Elbow plot ----
st.subheader("Elbow Plot")
k_range = range(1, 10)
sse = []
for k in k_range:
    km = KMeans(n_clusters=k, n_init=10, random_state=42)
    km.fit(X)
    sse.append(km.inertia_)

fig1, ax1 = plt.subplots()
ax1.plot(list(k_range), sse, marker="o")
ax1.set_xlabel("K")
ax1.set_ylabel("Sum of Squared Error (Inertia)")
ax1.set_title("Elbow Method for Optimal K")
st.pyplot(fig1)

# ---- Choose K ----
k = st.slider("Select number of clusters (K)", min_value=2, max_value=9, value=3)

# ---- Fit KMeans ----
km = KMeans(n_clusters=k, n_init=10, random_state=42)
y_pred = km.fit_predict(X)
df_result = df.copy()
df_result["cluster"] = y_pred

# ---- Scatter plot of clusters ----
st.subheader(f"Cluster Scatter Plot (K={k})")
fig2, ax2 = plt.subplots()
colors = plt.cm.get_cmap("tab10", k)
for cluster_id in range(k):
    subset = df_result[df_result["cluster"] == cluster_id]
    ax2.scatter(
        subset["petal length (cm)"],
        subset["petal width (cm)"],
        color=colors(cluster_id),
        label=f"Cluster {cluster_id}",
    )
ax2.set_xlabel("Petal Length (cm)")
ax2.set_ylabel("Petal Width (cm)")
ax2.legend()
st.pyplot(fig2)

st.subheader("Clustered Data")
st.dataframe(df_result)